# .github/workflows/build_apk.yml
name: Build APK

on:
  push:
    branches:
      - main  # Specify the branch you want to trigger this action on
  pull_request:
  workflow_dispatch:  # Allows the workflow to be manually triggered

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Check out repository
        uses: actions/checkout@v2

      # Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      # Download Android SDK
      - name: Install Android SDK
        env:
          ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk
        run: |
          sudo apt-get update
          sudo apt-get install -y wget tar unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          unzip commandlinetools-linux-9477386_latest.zip -d $ANDROID_SDK_ROOT/cmdline-tools
          mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
          rm commandlinetools-linux-9477386_latest.zip
          
      # Accept Android SDK licenses
      - name: Accept SDK Licenses
        env:
          ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

      # Install required SDK components
      - name: Install Android SDK packages
        env:
          ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk
        run: |
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

      # Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Build the project
      - name: Build APK
        run: ./gradlew assembleRelease

      # Upload the APK as an artifact using v3
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk
